imports:
    - { resource: services_legacy.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nimble\ElasticBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    Nimble\ElasticBundle\Client\ClientFactory:
        calls:
            - [setContainer, ['@service_container']]

    nimble_elastic.client_prototype:
        abstract: true
        factory:
            - '@Nimble\ElasticBundle\Client\ClientFactory'
            - createClient

    Nimble\ElasticBundle\Index\IndexManager: ~
    Nimble\ElasticBundle\Synchronizer\SynchronizerManager: ~
    Nimble\ElasticBundle\Transformer\TransformerManager: ~
    Nimble\ElasticBundle\Populator\PopulatorManager: ~
    Nimble\ElasticBundle\Doctrine\ORM\LifecycleEventSubscriber: ~

    Nimble\ElasticBundle\Command\PopulateCommand:
        tags: ['console.command']

    Nimble\ElasticBundle\Command\ResetCommand:
        tags: ['console.command']